SELECT
  `tabStudent Admission UCC`.`name` AS `name`,
  `tabStudent Admission UCC`.`creation` AS `creation`,
  `tabStudent Admission UCC`.`modified` AS `modified`,
  `tabStudent Admission UCC`.`modified_by` AS `modified_by`,
  `tabStudent Admission UCC`.`owner` AS `owner`,
  `tabStudent Admission UCC`.`docstatus` AS `docstatus`,
  `tabStudent Admission UCC`.`parent` AS `parent`,
  `tabStudent Admission UCC`.`parentfield` AS `parentfield`,
  `tabStudent Admission UCC`.`parenttype` AS `parenttype`,
  `tabStudent Admission UCC`.`idx` AS `idx`,
  `tabStudent Admission UCC`.`student_contract` AS `student_contract`,
  `tabStudent Admission UCC`.`amended_from` AS `amended_from`,
  `tabStudent Admission UCC`.`_user_tags` AS `_user_tags`,
  `tabStudent Admission UCC`.`_comments` AS `_comments`,
  `tabStudent Admission UCC`.`_assign` AS `_assign`,
  `tabStudent Admission UCC`.`_liked_by` AS `_liked_by`,
  `tabStudent Admission UCC`.`date` AS `date`,
  `tabStudent Admission UCC`.`name_of_parent` AS `name_of_parent`,
  `tabStudent Admission UCC`.`parent_signature` AS `parent_signature`,
  `tabStudent Admission UCC`.`student_signature` AS `student_signature`,
  `tabStudent Admission UCC`.`commencement_date` AS `commencement_date`,
  `tabStudent Admission UCC`.`completion_date` AS `completion_date`,
  `tabStudent Admission UCC`.`date_of_commencement` AS `date_of_commencement`,
  `tabStudent Admission UCC`.`holiday` AS `holiday`,
  `tabStudent Admission UCC`.`assessment_period` AS `assessment_period`,
  `tabStudent Admission UCC`.`examination_release_date` AS `examination_release_date`,
  `tabStudent Admission UCC`.`conferment_date` AS `conferment_date`,
  `tabStudent Admission UCC`.`no_of_instalment` AS `no_of_instalment`,
  `tabStudent Admission UCC`.`total_fee` AS `total_fee`,
  `tabStudent Admission UCC`.`total` AS `total`,
  `tabStudent Admission UCC`.`no_of_payment` AS `no_of_payment`,
  `tabStudent Admission UCC`.`payment_schedule` AS `payment_schedule`,
  `tabStudent Admission UCC`.`workflow_state` AS `workflow_state`,
  `tabStudent Admission UCC`.`conditional` AS `conditional`,
  `tabStudent Admission UCC`.`based_on` AS `based_on`,
  `tabStudent Admission UCC`.`student_applicant` AS `student_applicant`,
  `tabStudent Admission UCC`.`contract_start` AS `contract_start`,
  `tabStudent Admission UCC`.`contract_end` AS `contract_end`,
  `tabStudent Admission UCC`.`student_batch` AS `student_batch`,
  `tabStudent Admission UCC`.`instalment_template` AS `instalment_template`,
  `tabStudent Admission UCC`.`student_signed_date` AS `student_signed_date`,
  `tabStudent Admission UCC`.`pre_course_counseling` AS `pre_course_counseling`,
  `tabStudent Admission UCC`.`student_name` AS `student_name`,
  `tabStudent Admission UCC`.`fees_template` AS `fees_template`,
  `tabStudent Admission UCC`.`sales_invoice` AS `sales_invoice`,
  `tabStudent Admission UCC`.`email_sent` AS `email_sent`,
  `tabStudent Admission UCC`.`agent` AS `agent`,
  `tabStudent Admission UCC`.`interview_date` AS `interview_date`,
  `tabStudent Admission UCC`.`note` AS `note`,
  `tabStudent Admission UCC`.`letter_head` AS `letter_head`,
  `tabStudent Admission UCC`.`welcome_email_sent` AS `welcome_email_sent`,
  `tabStudent Admission UCC`.`document_control` AS `document_control`,
  `tabStudent Admission UCC`.`include_industrial_attachements` AS `include_industrial_attachements`,
  `tabStudent Admission UCC`.`duration_of_the_industrial_attachment` AS `duration_of_the_industrial_attachment`,
  `tabStudent Admission UCC`.`program` AS `program`,
  `tabStudent Admission UCC`.`customer` AS `customer`,
  `tabStudent Admission UCC`.`pre_course` AS `pre_course`,
  `tabStudent Admission UCC`.`checklist_template` AS `checklist_template`,
  `tabStudent Admission UCC`.`student` AS `student`,
  `tabStudent Admission UCC`.`approved_by` AS `approved_by`,
  `tabStudent Admission UCC`.`date_approved` AS `date_approved`,
  `tabStudent Admission UCC`.`approver_name` AS `approver_name`,
  `tabStudent Admission UCC`.`app_by` AS `app_by`,
  `tabStudent Admission UCC`.`application_status` AS `application_status`,
  `tabStudent Admission UCC`.`principal_signed_date` AS `principal_signed_date`,
  `tabStudent Admission UCC`.`parent_signature_1` AS `parent_signature_1`,
  `tabStudent Admission UCC`.`parent_signature_image_1` AS `parent_signature_image_1`,
  `tabStudent Admission UCC`.`parent_signature_2` AS `parent_signature_2`,
  `tabStudent Admission UCC`.`parent_signature_image_2` AS `parent_signature_image_2`,
  `tabStudent Admission UCC`.`parent_signature_3` AS `parent_signature_3`,
  `tabStudent Admission UCC`.`parent_signature_image_3` AS `parent_signature_image_3`,
  `tabStudent Admission UCC`.`student_signature_1` AS `student_signature_1`,
  `tabStudent Admission UCC`.`student_signature_image_1` AS `student_signature_image_1`,
  `tabStudent Admission UCC`.`student_signature_2` AS `student_signature_2`,
  `tabStudent Admission UCC`.`student_signature_image_2` AS `student_signature_image_2`,
  `tabStudent Admission UCC`.`student_signature_3` AS `student_signature_3`,
  `tabStudent Admission UCC`.`student_signature_image_3` AS `student_signature_image_3`,
  `tabStudent Admission UCC`.`parentguardian` AS `parentguardian`,
  `tabStudent Admission UCC`.`contract_sent_date` AS `contract_sent_date`,
  `tabStudent Admission UCC`.`contract_signed_by_student_date` AS `contract_signed_by_student_date`,
  `tabStudent Admission UCC`.`solar_file_number_issued_date` AS `solar_file_number_issued_date`,
  `tabStudent Admission UCC`.`stp_application_submitted_date` AS `stp_application_submitted_date`,
  `tabStudent Admission UCC`.`stp_application_signed` AS `stp_application_signed`,
  `tabStudent Admission UCC`.`stp_approved_date` AS `stp_approved_date`,
  `tabStudent Admission UCC`.`stp_collection_date` AS `stp_collection_date`,
  `tabStudent Admission UCC`.`contract_url` AS `contract_url`,
  `tabStudent Admission UCC`.`medical_examination_contract` AS `medical_examination_contract`,
  `tabStudent Admission UCC`.`medical_examination_contract_stamp` AS `medical_examination_contract_stamp`,
  `tabStudent Admission UCC`.`taxes_and_charges_template` AS `taxes_and_charges_template`,
  `tabStudent Admission UCC`.`amount_with_gst` AS `amount_with_gst`,
  `tabStudent Admission UCC`.`instalment_amount_with_gst` AS `instalment_amount_with_gst`,
  `tabStudent Admission UCC`.`student_stp_id` AS `student_stp_id`,
  `tabStudent Admission UCC`.`override_dates` AS `override_dates`,
  `tabStudent Admission UCC`.`stp_expiry_date` AS `stp_expiry_date`,
  `tabStudent Admission UCC`.`ica_status` AS `ica_status`,
  `tabStudent Admission UCC`.`notes` AS `notes`,
  `tabStudent Admission UCC`.`orientation_date` AS `orientation_date`,
  `tabStudent Admission UCC`.`custom_medical_and_tc` AS `custom_medical_and_tc`,
  `tabStudent Admission UCC`.`medical_and_t_and_c` AS `medical_and_t_and_c`,
  `tabStudent Admission UCC`.`student_ice_application_id` AS `student_ice_application_id`,
  `tabStudent Admission UCC`.`student_ica_application_id` AS `student_ica_application_id`,
  `tabStudent Admission UCC`.`student_identification` AS `student_identification`,
  `tabStudent Admission UCC`.`student_identification_number` AS `student_identification_number`,
  `tabStudent Admission UCC`.`insurance_date_fee` AS `insurance_date_fee`,
  `tabStudent Admission UCC`.`student_signed_date` - `tabStudent Admission UCC`.`pre_course_counseling` AS `Process Duration`,
  `Student Applicant Model - Name`.`name` AS `Student Applicant Model - Name__name`,
  `Student Applicant Model - Name`.`creation` AS `Student Applicant Model - Name__creation`,
  `Student Applicant Model - Name`.`modified` AS `Student Applicant Model - Name__modified`,
  `Student Applicant Model - Name`.`modified_by` AS `Student Applicant Model - Name__modified_by`,
  `Student Applicant Model - Name`.`owner` AS `Student Applicant Model - Name__owner`,
  `Student Applicant Model - Name`.`docstatus` AS `Student Applicant Model - Name__docstatus`,
  `Student Applicant Model - Name`.`parent` AS `Student Applicant Model - Name__parent`,
  `Student Applicant Model - Name`.`parentfield` AS `Student Applicant Model - Name__parentfield`,
  `Student Applicant Model - Name`.`parenttype` AS `Student Applicant Model - Name__parenttype`,
  `Student Applicant Model - Name`.`idx` AS `Student Applicant Model - Name__idx`,
  `Student Applicant Model - Name`.`first_name` AS `Student Applicant Model - Name__first_name`,
  `Student Applicant Model - Name`.`middle_name` AS `Student Applicant Model - Name__middle_name`,
  `Student Applicant Model - Name`.`last_name` AS `Student Applicant Model - Name__last_name`,
  `Student Applicant Model - Name`.`program` AS `Student Applicant Model - Name__program`,
  `Student Applicant Model - Name`.`paid` AS `Student Applicant Model - Name__paid`,
  `Student Applicant Model - Name`.`naming_series` AS `Student Applicant Model - Name__naming_series`,
  `Student Applicant Model - Name`.`application_status` AS `Student Applicant Model - Name__application_status`,
  `Student Applicant Model - Name`.`application_date` AS `Student Applicant Model - Name__application_date`,
  `Student Applicant Model - Name`.`academic_year` AS `Student Applicant Model - Name__academic_year`,
  `Student Applicant Model - Name`.`academic_term` AS `Student Applicant Model - Name__academic_term`,
  `Student Applicant Model - Name`.`student_admission` AS `Student Applicant Model - Name__student_admission`,
  `Student Applicant Model - Name`.`image` AS `Student Applicant Model - Name__image`,
  `Student Applicant Model - Name`.`date_of_birth` AS `Student Applicant Model - Name__date_of_birth`,
  `Student Applicant Model - Name`.`gender` AS `Student Applicant Model - Name__gender`,
  `Student Applicant Model - Name`.`blood_group` AS `Student Applicant Model - Name__blood_group`,
  `Student Applicant Model - Name`.`student_email_id` AS `Student Applicant Model - Name__student_email_id`,
  `Student Applicant Model - Name`.`student_mobile_number` AS `Student Applicant Model - Name__student_mobile_number`,
  `Student Applicant Model - Name`.`nationality` AS `Student Applicant Model - Name__nationality`,
  `Student Applicant Model - Name`.`address_line_1` AS `Student Applicant Model - Name__address_line_1`,
  `Student Applicant Model - Name`.`address_line_2` AS `Student Applicant Model - Name__address_line_2`,
  `Student Applicant Model - Name`.`pincode` AS `Student Applicant Model - Name__pincode`,
  `Student Applicant Model - Name`.`city` AS `Student Applicant Model - Name__city`,
  `Student Applicant Model - Name`.`state` AS `Student Applicant Model - Name__state`,
  `Student Applicant Model - Name`.`title` AS `Student Applicant Model - Name__title`,
  `Student Applicant Model - Name`.`amended_from` AS `Student Applicant Model - Name__amended_from`,
  `Student Applicant Model - Name`.`_user_tags` AS `Student Applicant Model - Name___user_tags`,
  `Student Applicant Model - Name`.`_comments` AS `Student Applicant Model - Name___comments`,
  `Student Applicant Model - Name`.`_assign` AS `Student Applicant Model - Name___assign`,
  `Student Applicant Model - Name`.`_liked_by` AS `Student Applicant Model - Name___liked_by`,
  `Student Applicant Model - Name`.`alias` AS `Student Applicant Model - Name__alias`,
  `Student Applicant Model - Name`.`name_in_chinese` AS `Student Applicant Model - Name__name_in_chinese`,
  `Student Applicant Model - Name`.`country_of_birth` AS `Student Applicant Model - Name__country_of_birth`,
  `Student Applicant Model - Name`.`religion` AS `Student Applicant Model - Name__religion`,
  `Student Applicant Model - Name`.`race` AS `Student Applicant Model - Name__race`,
  `Student Applicant Model - Name`.`occupation` AS `Student Applicant Model - Name__occupation`,
  `Student Applicant Model - Name`.`marital_status` AS `Student Applicant Model - Name__marital_status`,
  `Student Applicant Model - Name`.`passport_no` AS `Student Applicant Model - Name__passport_no`,
  `Student Applicant Model - Name`.`sex` AS `Student Applicant Model - Name__sex`,
  `Student Applicant Model - Name`.`postal_code` AS `Student Applicant Model - Name__postal_code`,
  `Student Applicant Model - Name`.`fin_no` AS `Student Applicant Model - Name__fin_no`,
  `Student Applicant Model - Name`.`nric_no` AS `Student Applicant Model - Name__nric_no`,
  `Student Applicant Model - Name`.`date_of_issue_passport` AS `Student Applicant Model - Name__date_of_issue_passport`,
  `Student Applicant Model - Name`.`date_of_expiry_passport` AS `Student Applicant Model - Name__date_of_expiry_passport`,
  `Student Applicant Model - Name`.`date_of_issue_fin` AS `Student Applicant Model - Name__date_of_issue_fin`,
  `Student Applicant Model - Name`.`date_of_expiry_fin` AS `Student Applicant Model - Name__date_of_expiry_fin`,
  `Student Applicant Model - Name`.`address` AS `Student Applicant Model - Name__address`,
  `Student Applicant Model - Name`.`phone_number` AS `Student Applicant Model - Name__phone_number`,
  `Student Applicant Model - Name`.`ic_type` AS `Student Applicant Model - Name__ic_type`,
  `Student Applicant Model - Name`.`residence_status` AS `Student Applicant Model - Name__residence_status`,
  `Student Applicant Model - Name`.`student_type` AS `Student Applicant Model - Name__student_type`,
  `Student Applicant Model - Name`.`student_admission_ucc` AS `Student Applicant Model - Name__student_admission_ucc`,
  `Student Applicant Model - Name`.`agent` AS `Student Applicant Model - Name__agent`,
  `Student Applicant Model - Name`.`student_category` AS `Student Applicant Model - Name__student_category`,
  `Student Applicant Model - Name`.`country` AS `Student Applicant Model - Name__country`,
  `Student Applicant Model - Name`.`custom_consent` AS `Student Applicant Model - Name__custom_consent`,
  `Student Applicant Model - Name`.`custom_precourse_consent` AS `Student Applicant Model - Name__custom_precourse_consent`,
  `Student Applicant Model - Name`.`custom_precourse_counselling_confirmation` AS `Student Applicant Model - Name__custom_precourse_co_acd273e9`,
  `Student Applicant Model - Name`.`custom_marketing_consent` AS `Student Applicant Model - Name__custom_marketing_consent`,
  `Student Applicant Model - Name`.`custom_digital_learning_and_recording_consent` AS `Student Applicant Model - Name__custom_digital_lear_d0b0fdc3`,
  `Student Applicant Model - Name`.`custom_confirmation_and_understanding` AS `Student Applicant Model - Name__custom_confirmation_9db5c028`,
  `Student Applicant Model - Name`.`custom_commitment_and_documentation` AS `Student Applicant Model - Name__custom_commitment_a_4cbb9dd7`,
  `Student Applicant Model - Name`.`custom_any_special_need` AS `Student Applicant Model - Name__custom_any_special_need`,
  `Student Applicant Model - Name`.`custom_special_needs_detail` AS `Student Applicant Model - Name__custom_special_needs_detail`,
  `Student Applicant Model - Name`.`custom_customer` AS `Student Applicant Model - Name__custom_customer`,
  `Student Applicant Model - Name`.`custom_checklist_template` AS `Student Applicant Model - Name__custom_checklist_template`,
  `Student Applicant Model - Name`.`custom_approved_by` AS `Student Applicant Model - Name__custom_approved_by`,
  `Student Applicant Model - Name`.`custom_approver_name` AS `Student Applicant Model - Name__custom_approver_name`,
  `Student Applicant Model - Name`.`custom_comments` AS `Student Applicant Model - Name__custom_comments`,
  `Student Applicant Model - Name`.`custom_date_approved` AS `Student Applicant Model - Name__custom_date_approved`
FROM
  `tabStudent Admission UCC`
  LEFT JOIN (
    SELECT
      `__mb_source`.`name` AS `name`,
      `__mb_source`.`creation` AS `creation`,
      `__mb_source`.`modified` AS `modified`,
      `__mb_source`.`modified_by` AS `modified_by`,
      `__mb_source`.`owner` AS `owner`,
      `__mb_source`.`docstatus` AS `docstatus`,
      `__mb_source`.`parent` AS `parent`,
      `__mb_source`.`parentfield` AS `parentfield`,
      `__mb_source`.`parenttype` AS `parenttype`,
      `__mb_source`.`idx` AS `idx`,
      `__mb_source`.`first_name` AS `first_name`,
      `__mb_source`.`middle_name` AS `middle_name`,
      `__mb_source`.`last_name` AS `last_name`,
      `__mb_source`.`program` AS `program`,
      `__mb_source`.`paid` AS `paid`,
      `__mb_source`.`naming_series` AS `naming_series`,
      `__mb_source`.`application_status` AS `application_status`,
      `__mb_source`.`application_date` AS `application_date`,
      `__mb_source`.`academic_year` AS `academic_year`,
      `__mb_source`.`academic_term` AS `academic_term`,
      `__mb_source`.`student_admission` AS `student_admission`,
      `__mb_source`.`image` AS `image`,
      `__mb_source`.`date_of_birth` AS `date_of_birth`,
      `__mb_source`.`gender` AS `gender`,
      `__mb_source`.`blood_group` AS `blood_group`,
      `__mb_source`.`student_email_id` AS `student_email_id`,
      `__mb_source`.`student_mobile_number` AS `student_mobile_number`,
      `__mb_source`.`nationality` AS `nationality`,
      `__mb_source`.`address_line_1` AS `address_line_1`,
      `__mb_source`.`address_line_2` AS `address_line_2`,
      `__mb_source`.`pincode` AS `pincode`,
      `__mb_source`.`city` AS `city`,
      `__mb_source`.`state` AS `state`,
      `__mb_source`.`title` AS `title`,
      `__mb_source`.`amended_from` AS `amended_from`,
      `__mb_source`.`_user_tags` AS `_user_tags`,
      `__mb_source`.`_comments` AS `_comments`,
      `__mb_source`.`_assign` AS `_assign`,
      `__mb_source`.`_liked_by` AS `_liked_by`,
      `__mb_source`.`alias` AS `alias`,
      `__mb_source`.`name_in_chinese` AS `name_in_chinese`,
      `__mb_source`.`country_of_birth` AS `country_of_birth`,
      `__mb_source`.`religion` AS `religion`,
      `__mb_source`.`race` AS `race`,
      `__mb_source`.`occupation` AS `occupation`,
      `__mb_source`.`marital_status` AS `marital_status`,
      `__mb_source`.`passport_no` AS `passport_no`,
      `__mb_source`.`sex` AS `sex`,
      `__mb_source`.`postal_code` AS `postal_code`,
      `__mb_source`.`fin_no` AS `fin_no`,
      `__mb_source`.`nric_no` AS `nric_no`,
      `__mb_source`.`date_of_issue_passport` AS `date_of_issue_passport`,
      `__mb_source`.`date_of_expiry_passport` AS `date_of_expiry_passport`,
      `__mb_source`.`date_of_issue_fin` AS `date_of_issue_fin`,
      `__mb_source`.`date_of_expiry_fin` AS `date_of_expiry_fin`,
      `__mb_source`.`address` AS `address`,
      `__mb_source`.`phone_number` AS `phone_number`,
      `__mb_source`.`ic_type` AS `ic_type`,
      `__mb_source`.`residence_status` AS `residence_status`,
      `__mb_source`.`student_type` AS `student_type`,
      `__mb_source`.`student_admission_ucc` AS `student_admission_ucc`,
      `__mb_source`.`agent` AS `agent`,
      `__mb_source`.`student_category` AS `student_category`,
      `__mb_source`.`country` AS `country`,
      `__mb_source`.`custom_consent` AS `custom_consent`,
      `__mb_source`.`custom_precourse_consent` AS `custom_precourse_consent`,
      `__mb_source`.`custom_precourse_counselling_confirmation` AS `custom_precourse_counselling_confirmation`,
      `__mb_source`.`custom_marketing_consent` AS `custom_marketing_consent`,
      `__mb_source`.`custom_digital_learning_and_recording_consent` AS `custom_digital_learning_and_recording_consent`,
      `__mb_source`.`custom_confirmation_and_understanding` AS `custom_confirmation_and_understanding`,
      `__mb_source`.`custom_commitment_and_documentation` AS `custom_commitment_and_documentation`,
      `__mb_source`.`custom_any_special_need` AS `custom_any_special_need`,
      `__mb_source`.`custom_special_needs_detail` AS `custom_special_needs_detail`,
      `__mb_source`.`custom_customer` AS `custom_customer`,
      `__mb_source`.`custom_checklist_template` AS `custom_checklist_template`,
      `__mb_source`.`custom_approved_by` AS `custom_approved_by`,
      `__mb_source`.`custom_approver_name` AS `custom_approver_name`,
      `__mb_source`.`custom_comments` AS `custom_comments`,
      `__mb_source`.`custom_date_approved` AS `custom_date_approved`
    FROM
      (
        select
          *
        from
          `tabStudent Applicant`
      ) AS `__mb_source`
  ) AS `Student Applicant Model - Name` ON `tabStudent Admission UCC`.`student_applicant` = `Student Applicant Model - Name`.`name`
WHERE
  `tabStudent Admission UCC`.`docstatus` = 1
LIMIT
  1048575